### ISSUE TITLE
negative review count for custom queue builder

### ISSUE THREAD

**Issue by lovac42** [lovac42/HoochieMama#10]
When using the custom queue builder, there is an issue with miscounts when the parent deck contains subdecks within subdecks and more subdecks within those subdecks. Currently, it does not respect the limits imposed by the middle subdecks, only the selected parent and grandchild.

This can be avoided by not setting a limit on mid level decks (e.g. 9999). The actual fix will require checking the limit on sibling decks as the queue is built and offsetting the values from the total limit.

**Comment by lovac42** [comment]
You posted in the wrong place.
Each addon is separate, their configs has nothing to do with one another.

**Comment by cjdduarte** [comment]
OK.
