### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by s73v3nd** [lovac42/HoochieMama#18]
Hey, I wanted to change the default settings so that unrestricted random mode is always on instead of having to scroll to it each time. Is there a way to do this?

**Comment by lovac42** [comment]
It's in the sort.py file, just swap line 8 to line 25: https://github.com/lovac42/HoochieMama/blob/v0.3.1/src/hoochie_mama/sort.py#L8

Change the key so that 0 becomes 11, and 11 becomes 0.

**Comment by s73v3nd** [comment]
Great, thanks a lot!
