### ISSUE TITLE
Error with Anki 2.1.20 Beta 5

### ISSUE THREAD

**Issue by Kosezu** [lovac42/HoochieMama#19]
When loading 'HoochieMama Randomize Rev Queue':
Traceback (most recent call last):
  File "aqt/addons.py", line 192, in loadAddons
  File "/Users/csosborn/Library/Application Support/Anki2/addons21/1460733408/__init__.py", line 8, in <module>
    from . import hoochieMama
  File "/Users/csosborn/Library/Application Support/Anki2/addons21/1460733408/hoochieMama.py", line 218, in <module>
    oldSync=anki.sync.Syncer.sync
AttributeError: module 'anki' has no attribute 'sync'

**Comment by khonkhortisan** [comment]
[info] https://anki.tenderapp.com/discussions/beta-testing/1708-anki-2120-beta

**Comment by lovac42** [comment]
I tested this briefly, seems to work, but my test collection is too small to determine working condition.

[hoochie_mama_v0.3.2beta_Anki21.ankiaddon.zip](https://github.com/lovac42/HoochieMama/files/4151555/hoochie_mama_v0.3.2beta_Anki21.ankiaddon.zip)

If you used it for sometime and it doesn't force or require a full sync, then it's working. The review count on the server and the one reported by Anki desktop (with this addon) must be the same, otherwise it will force a full sync. That's when you know it's not working.

**Comment by jesslikesit** [comment]
> I tested this briefly, seems to work, but my test collection is too small to determine working condition.
> 
> [hoochie_mama_v0.3.2beta_Anki21.ankiaddon.zip](https://github.com/lovac42/HoochieMama/files/4151555/hoochie_mama_v0.3.2beta_Anki21.ankiaddon.zip)
> 
> If you used it for sometime and it doesn't force or require a full sync, then it's working. The review count on the server and the one reported by Anki desktop (with this addon) must be the same, otherwise it will force a full sync. That's when you know it's not working.

This doesn't work for me. After I've moved the file to my addons folder, it tells me the add on could not be installed

**Comment by lovac42** [comment]
@jesslikesit : rename .zip to .ankiaddon. This is not a valid extension allowed by github for file sharing.

**Comment by jesslikesit** [comment]
> @jesslikesit : rename .zip to .ankiaddon. This is not a valid extension allowed by github for file sharing.

@lovac42 Hey! Thanks for responding but I'm not sure what you mean, since the file is already named hoochie_mama_v0.3.2beta_Anki21.ankiaddon  (I unziped it)

**Comment by lovac42** [comment]
@jesslikesit : don't worry about it, just wait for the proper release when it's ready :-)

**Comment by lovac42** [comment]
The latest update seems to be working fine, so I am closing this. Open this again or file another ticket if you run into any problems.
