### ISSUE TITLE
Getting an error like this.Help me please

### ISSUE THREAD

**Issue by kinkeymonkey161** [lovac42/HoochieMama#21]
Getting error like this.Help me

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-25 08:55:12

Caught exception:
Traceback (most recent call last):
File "C:\Users\G******n\AppData\Roaming\Anki2\addons21\1460733408\prefmenu.py", line 86, in <lambda>
lambda:onClickEx(self.hoochieMamaExRand,"hoochieMama_extra_shuffle")
File "C:\Users\G******n\AppData\Roaming\Anki2\addons21\1460733408\prefmenu.py", line 140, in onClickEx
idx = mw.col.conf["hoochieMamaSort"]
KeyError: 'hoochieMamaSort'

**Comment by lovac42** [comment]
I thought I fixed this, I'll look into it. For now, you can get around it by turning on and off the check boxes. It only occurs to new profiles.

**Comment by lovac42** [comment]
@kinkeymonkey161 Thanks for letting me know. This is fixed in the recent update. It's just a minor warning. Click on check addon update in addon manager to update to the latest version.

**Comment by kinkeymonkey161** [comment]
Thanks a lot man. It's perfect now
