### ISSUE TITLE
Update status? Willing to pay

### ISSUE THREAD

**Issue by AaronCartwright** [lovac42/HoochieMama#27]
Hello Lovac42,

I'm wondering if this add-on will be updated for this cycle? I'm willing pay offer $150 for the update if that can help speed up things. @lovac42

**Comment by lovac42** [comment]
Thanks, but the trouble isn't worth the money. I rather not be obligated to this by taking payment. I'll push an update once I think of a way to get around the technical issues. Thanks for understanding.

**Comment by AaronCartwright** [comment]
No worries! Thanks for the work you've done. Just having an acknowledgement is enough, Cheers
