### ISSUE TITLE
This keeps popping up. 

### ISSUE THREAD

**Issue by ghost** [lovac42/HoochieMama#29]
<img width="412" alt="Screen Shot 2021-11-25 at 9 34 29 PM" src="https://user-images.githubusercontent.com/82780775/143532068-c1cf37dc-5691-478d-9be6-5c220cb83922.png">

Not certain what the source of the problem is.

**Comment by lovac42** [comment]
This addon is not needed anymore, you may delete it.
Don't download addons that says "Legacy" on it.
