### ISSUE TITLE
Showing Reviews over limit from subdeck

### ISSUE THREAD

**Issue by xd1986k** [lovac42/HoochieMama#3]
Hello
I have a "G" subdeck capped to 1 new and 4 reviews. With this addon enabled when I go through my main deck, it does not respect the limits set in the subdeck and makes me go through all overdue cards.

**Comment by lovac42** [comment]
Yup that is how the V2 scheduler works. It uses the limit from the parent deck. This is written in the updated readmes.

**Comment by xd1986k** [comment]
My bad. I'm not very familiar with V2. Thanks for clearing that up for me.

**Comment by lovac42** [comment]
I added some custom codes to enforce subdeck limits. You can test it out: https://github.com/lovac42/HoochieMama/blob/deque/src/hoochieMama.py
Works for v1 and v2.

**Comment by xd1986k** [comment]
I just tried this out and it works perfectly except for in filtered decks. Thanks alot.
