### ISSUE TITLE
After enabling HoochieMama it still doesn't randomize queue

### ISSUE THREAD

**Issue by Hnous927** [lovac42/HoochieMama#4]
First, thank you very much for back porting this from the v2 scheduler. This feature is much wanted!

I've activated this addon in preferences. However, when I review the main deck, it still doesn't randomize the sub-decks.

Config:
Anki Version 2.0.48
HoochieMama Version: 0.0.9
Windows 10
I don't have serenityNow installed; I've deleted the addon"Change Order of Review Cards in Regular Decks"

What possibly could have gone wrong?
Thanks again

**Comment by lovac42** [comment]
On line 63, there is a print statement, if you enable it, it'll tell you if this addon is enabled or not. You will need a debugger addon to see this info on windows: https://ankiweb.net/shared/info/2099968349.

Also this addon was only tested on anki 2.0.52, so update if you can.

**Comment by Hnous927** [comment]
Thanks for getting back to me! I appreciate it!
I've updated Anki to the latest version 2.0.52; I've updated HoochieMama Version to 0.1.3. Enabled it in Preference. I've made a dummy deck with 3 sub-ducks and all new cards. Still no luck.

I've removed the # prefix in line 50, but it doesn't show anything during review. I've tried removing the # prefix in line 49; still no luck. My hunch is that the addon is somehow not activated.

Thanks again for looking into my issue!

**Comment by lovac42** [comment]
V2 only randomizes review cards, not new cards or learning cards. If you don't see any popup text after enable line 50, then the addon is not actived. Try using it without any other addons.

**Comment by Hnous927** [comment]
I apologize. I thought the addon (or V2 in general) would randomize everything, including new and learning cards. I should've read the description more closely.
I don't have any review card at the moment. If I encounter further problems I will report back. Thank you!
