### ISSUE TITLE
About this addon

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/HoochieMama#7]
Does this addon randomize new or learning cards?

**Comment by lovac42** [comment]
Nope. Lrn cards depend on time, so you would randomize 1-2 cards at most. New cards are harder to learn if you jumbo them and with Cardistry, I'm getting 1-2 new cards only per subdeck. No point in randomizing such small amounts.

**Comment by cjdduarte** [comment]
Does Cardylist Randomize? I'll check
